### ISSUE TITLE
ECDH wycheproof test cases

### ISSUE THREAD

**Issue by bboilot-ledger** [quarkslab/crypto-condor#11]
Hi @JulioLoayzaM :wave: 

I am having an issue while trying to use wycheproof test cases for the ECDH primitive using `brainpoolP256r1` and `secp256k1` curves.
When I try to run the tests, I get the following stack trace:
```
  File "/home/user/Documents/apps/app-condor/condor/primitives/ecdh.py", line 93, in run
    res = ECDH.test_exchange(
  File "/home/user/Documents/apps/app-condor/venv/lib/python3.10/site-packages/crypto_condor/primitives/ECDH.py", line 533, in test_exchange
    rdict.add(test_exchange_wycheproof(ecdh, curve))
  File "/home/user/Documents/apps/app-condor/venv/lib/python3.10/site-packages/crypto_condor/primitives/ECDH.py", line 420, in test_exchange_wycheproof
    secret = int.from_bytes(test.secret, "big")
AttributeError: secret
```

Looking at the vectors and the protobuf documentation I am guessing that `secret` attribute does not exists. It may be a typo. From my understanding, we could use `test.private` instead. If this is right, I can open a PR if you want.

**Comment by JulioLoayzaM** [comment]
Hi @bboilot-ledger,

I can reproduce with P-256 by modifying the Python example 1.

You're correct, it should be `test.private` instead of `test.secret`. However, while testing this fix I've found a couple of bugs lurking in `test_exchange_wycheproof`. The main problem is that this function isn't actually tested because of a setup error (Wycheproof doesn't provide vectors for P-192) and a bug in `run_wrapper_python`. If you don't mind, I'll fix this along with the other bugs so that I can add some context in the commit message. But if you prefer a PR let me know!

**Comment by JulioLoayzaM** [comment]
Hi @bboilot-ledger,

New release 2024.08.23 pushed with the fix for the ECDH bugs above. :D
